/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости бэкенда */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить код подтверждения — уходит в Telegram на указанный номер */
        post: operations["AuthController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обменять код из Telegram на JWT */
        post: operations["AuthController_verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего пользователя */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Выбрать никнейм; он же подтверждает автоматически выданный при регистрации */
        patch: operations["AuthController_setNickname"];
        trace?: never;
    };
    "/api/houses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все дома с отзывами — пины на карте */
        get: operations["HousesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/houses/by-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дом с квартирами по адресу; house = null, если отзывов ещё нет */
        get: operations["HousesController_byAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Свои отзывы с адресами квартир, недавно изменённые сверху */
        get: operations["ReviewsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать отзыв; дом и квартира заводятся автоматически */
        post: operations["ReviewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить свой отзыв; правка возвращает его на проверку модератору */
        patch: operations["ReviewsController_update"];
        trace?: never;
    };
    "/api/apartments/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отзывы одной квартиры, новые сверху */
        get: operations["ApartmentReviewsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Текущее состояние сервиса
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @description Имя сервиса, ответившего на запрос
             * @example back
             */
            service: string;
            /**
             * @description Аптайм процесса в секундах
             * @example 1234
             */
            uptime: number;
            /**
             * Format: date-time
             * @description Время формирования ответа, ISO 8601
             * @example 2026-08-10T12:00:00.000Z
             */
            timestamp: string;
        };
        RequestCodeDto: {
            /**
             * @description Телефон в российском формате; номера других стран не обслуживаем
             * @example +79991234567
             */
            phone: string;
            /**
             * @description Токен SmartCaptcha. Опционален в схеме, потому что в разработке ключей может
             *     не быть; когда серверный ключ задан, отсутствие токена даёт 400 в CaptchaService.
             */
            captchaToken?: string;
        };
        VerifyCodeDto: {
            /**
             * @description Телефон в российском формате; номера других стран не обслуживаем
             * @example +79991234567
             */
            phone: string;
            /**
             * @description Шестизначный код из Telegram
             * @example 123456
             */
            code: string;
        };
        UserDto: {
            /**
             * @description Телефон, на который выдан токен
             * @example +79991234567
             */
            phone: string;
            /**
             * @description Публичный ник; им подписаны отзывы
             * @example maxim_n
             */
            nickname: string;
            /** @description Идентификатор пользователя */
            id: string;
            /**
             * @description false — ник сгенерирован автоматически и пользователь его ещё не выбирал.
             *     Фронт по этому флагу показывает обязательный шаг ввода ника.
             */
            nicknameConfirmed: boolean;
        };
        AuthResponseDto: {
            /** @description Bearer-токен для заголовка Authorization */
            accessToken: string;
            /** @description Профиль вошедшего пользователя */
            user: components["schemas"]["UserDto"];
        };
        SetNicknameDto: {
            /**
             * @description Никнейм: буквы, цифры и подчёркивание, 3–20 символов. Пробелов нет
             *     намеренно — ник подписывает отзывы и читается как идентификатор.
             *     Занятость проверяется без учёта регистра.
             * @example maxim_n
             */
            nickname: string;
        };
        HousePinDto: {
            /** @description Идентификатор дома */
            id: string;
            /** @description Отображаемый адрес */
            address: string;
            lat: number;
            lon: number;
            /** @description Подтверждённых отзывов по всем квартирам дома */
            confirmedCount: number;
            /** @description Неподтверждённых отзывов по всем квартирам дома */
            pendingCount: number;
        };
        ApartmentSummaryDto: {
            /** @description Идентификатор квартиры */
            id: string;
            /** @description Номер квартиры */
            number: string;
            /** @description Подъезд */
            entrance: string;
            /** @description Подтверждённых отзывов */
            confirmedCount: number;
            /** @description Неподтверждённых отзывов */
            pendingCount: number;
        };
        HouseWithApartmentsDto: {
            /** @description Квартиры дома, по которым есть отзывы */
            apartments: components["schemas"]["ApartmentSummaryDto"][];
            id: string;
            address: string;
            lat: number;
            lon: number;
        };
        HouseLookupResponseDto: {
            /** @description null — по этому адресу ещё нет ни одного отзыва */
            house: components["schemas"]["HouseWithApartmentsDto"] | null;
        };
        /** @enum {string} */
        ReviewStatus: "pending" | "confirmed" | "rejected";
        MyReviewDto: {
            status: components["schemas"]["ReviewStatus"];
            /**
             * @description Начало периода съёма
             * @example 2024-03-12
             */
            periodFrom: string | null;
            /**
             * @description Конец периода съёма
             * @example 2025-04-12
             */
            periodTo: string | null;
            /** @description Причина отклонения от модератора; null — отзыв не отклоняли */
            rejectionReason: string | null;
            /**
             * @description Номер квартиры
             * @example 120
             */
            apartmentNumber: string;
            /**
             * @description Подъезд
             * @example 7
             */
            entrance: string;
            /** @description Идентификатор отзыва */
            id: string;
            /** @description Текст отзыва */
            text: string;
            /** @description Дата создания, ISO 8601 */
            createdAt: string;
            /** @description Дата последней правки, ISO 8601; по ней отсортирован список */
            updatedAt: string;
            /** @description Идентификатор квартиры, о которой отзыв */
            apartmentId: string;
            /** @description Адрес дома */
            address: string;
            /** @description Широта дома — к этой точке перелетает карта */
            lat: number;
            /** @description Долгота дома */
            lon: number;
        };
        CreateReviewDto: {
            /**
             * @description Номер квартиры
             * @example 120
             */
            apartmentNumber: string;
            /**
             * @description Подъезд; обязателен — API Яндекса его не отдаёт, вводится вручную
             * @example 7
             */
            entrance: string;
            /**
             * @description Кадастровый номер из выписки ЕГРН: округ:район:квартал:объект.
             *     Квартал — шесть или семь цифр, номер объекта — от одной.
             *     Тот же формат задаёт маска поля на фронте.
             * @example 77:01:0001075:1234
             */
            egrn: string;
            /**
             * @description Начало периода съёма, ISO-дата
             * @example 2024-03-12
             */
            periodFrom?: string;
            /**
             * @description Конец периода съёма, ISO-дата
             * @example 2025-04-12
             */
            periodTo?: string;
            /** @description Канонический адрес дома от геокодера */
            address: string;
            /** @description Широта дома */
            lat: number;
            /** @description Долгота дома */
            lon: number;
            /** @description Текст отзыва */
            text: string;
            /** @description Токен SmartCaptcha; обязателен, когда проверка капчи включена */
            captchaToken?: string;
        };
        ReviewCreatedDto: {
            status: components["schemas"]["ReviewStatus"];
            reviewId: string;
            houseId: string;
            apartmentId: string;
        };
        UpdateReviewDto: {
            /**
             * @description Начало периода съёма, ISO-дата
             * @example 2024-03-12
             */
            periodFrom?: string;
            /**
             * @description Конец периода съёма, ISO-дата
             * @example 2025-04-12
             */
            periodTo?: string;
            /** @description Текст отзыва */
            text: string;
            /** @description Токен SmartCaptcha; обязателен, когда проверка капчи включена */
            captchaToken?: string;
        };
        ReviewDto: {
            status: components["schemas"]["ReviewStatus"];
            /**
             * @description Начало периода съёма
             * @example 2024-03-12
             */
            periodFrom: string | null;
            /**
             * @description Конец периода съёма
             * @example 2025-04-12
             */
            periodTo: string | null;
            /** @description Идентификатор отзыва */
            id: string;
            /** @description Никнейм автора */
            authorName: string;
            /** @description Текст отзыва */
            text: string;
            /** @description Дата создания, ISO 8601 */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    AuthController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeDto"];
            };
        };
        responses: {
            /** @description Код отправлен на указанный номер */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не пройдена проверка капчи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Код на этот номер запрошен меньше минуты назад */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Код не отправлен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Неверный, истёкший код или исчерпаны попытки */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_setNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetNicknameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Никнейм уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HousesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousePinDto"][];
                };
            };
        };
    };
    HousesController_byAddress: {
        parameters: {
            query: {
                /** @description Канонический адрес, как его вернул геокодер */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseLookupResponseDto"];
                };
            };
        };
    };
    ReviewsController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyReviewDto"][];
                };
            };
            /** @description Нет или истёк токен авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCreatedDto"];
                };
            };
            /** @description Нет или истёк токен авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не пройдена проверка капчи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyReviewDto"];
                };
            };
            /** @description Нет или истёк токен авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не пройдена проверка капчи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Своего отзыва с таким идентификатором нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Отзыв на проверке у модератора */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApartmentReviewsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"][];
                };
            };
        };
    };
}
