/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости бэкенда */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Начать вход: мобильная авторизация на указанный номер. Дальше человек либо
         *     подтверждает вход на SIM-карте, либо получает от провайдера код в SMS —
         *     что именно, говорит опрос статуса (`session`), а не этот ответ.
         */
        post: operations["AuthController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Узнать, чем кончилась заявка. Фронт опрашивает этот метод, пока идёт
         *     мобильная авторизация; при подтверждении в ответе сразу токен.
         *
         *     POST, а не GET: телефон и секрет сессии в query-строке осели бы в логах nginx.
         */
        post: operations["AuthController_pollSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mobile-id/callback/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Приёмник статусов мобильной авторизации.
         *
         *     Тело приходит без подписи, поэтому решения по нему не принимаются: приёмник
         *     только помечает заявку как требующую перепроверки, а статус всё равно
         *     спрашивается у провайдера в `session`. Иначе тот, кто подберёт id заявки,
         *     прислал бы «status: 1» и получил чужой вход.
         *
         *     Секрет заявки в адресе — он же `sessionId`, выданный тому, кто вход начал:
         *     без него приёмник даже не ищет заявку.
         */
        post: operations["AuthController_mobileIdCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обменять код из сообщения на JWT */
        post: operations["AuthController_verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего пользователя */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Принять пользовательское соглашение и дать согласие на обработку
         *     персональных данных. Одно действие на оба документа: согласие в
         *     интерфейсе одно и покрывает их вместе.
         *
         *     Идемпотентен: повторный вызов не сдвигает дату принятия.
         */
        post: operations["AuthController_acceptConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/email/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Прислать код подтверждения почты уже вошедшему человеку. Нужен потому, что
         *     отзыв подписывается почтой: на неё уходит решение модератора.
         */
        post: operations["AuthController_requestEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подтвердить почту кодом из письма и привязать её к аккаунту */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Выбрать никнейм; он же подтверждает автоматически выданный при регистрации */
        patch: operations["AuthController_setNickname"];
        trace?: never;
    };
    "/api/houses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все дома с отзывами — пины на карте */
        get: operations["HousesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/houses/by-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дом с квартирами по адресу; house = null, если отзывов ещё нет */
        get: operations["HousesController_byAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Свои отзывы с адресами квартир, недавно изменённые сверху */
        get: operations["ReviewsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать отзыв; дом и квартира заводятся автоматически */
        post: operations["ReviewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить свой отзыв; правка возвращает его на проверку модератору */
        patch: operations["ReviewsController_update"];
        trace?: never;
    };
    "/api/apartments/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отзывы одной квартиры, новые сверху */
        get: operations["ApartmentReviewsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Города, где есть подтверждённые отзывы */
        get: operations["CatalogController_cities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/cities/{citySlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Улицы города */
        get: operations["CatalogController_city"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/cities/{citySlug}/streets/{streetSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дома улицы */
        get: operations["CatalogController_street"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/cities/{citySlug}/streets/{streetSlug}/houses/{houseSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дом со всеми подтверждёнными отзывами */
        get: operations["CatalogController_house"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Текущее состояние сервиса
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @description Имя сервиса, ответившего на запрос
             * @example back
             */
            service: string;
            /**
             * @description Аптайм процесса в секундах
             * @example 1234
             */
            uptime: number;
            /**
             * Format: date-time
             * @description Время формирования ответа, ISO 8601
             * @example 2026-08-10T12:00:00.000Z
             */
            timestamp: string;
        };
        RequestCodeDto: {
            /**
             * @description Телефон в российском формате или адрес почты — вход принимает и то и другое,
             *     что именно, сервер решает по наличию собачки. Регэксп покрывает обе формы
             *     сразу: разбить на два поля значило бы заставить фронт угадывать до отправки.
             * @example +79991234567
             */
            login: string;
            /**
             * @description Токен SmartCaptcha. Опционален в схеме, потому что в разработке ключей может
             *     не быть; когда серверный ключ задан, отсутствие токена даёт 400 в CaptchaService.
             */
            captchaToken?: string;
        };
        RequestCodeResponseDto: {
            /**
             * @description Секрет для опроса статуса входа. Больше в ответе ничего нет намеренно:
             *     подтвердит человек вход на SIM-карте или провайдер перейдёт на код в SMS —
             *     на этом шаге ещё неизвестно, это выясняет опрос статуса.
             * @example 3f2a9c1d4b5e6f708192a3b4c5d6e7f8
             */
            sessionId: string;
        };
        SessionPollDto: {
            /**
             * @description Телефон в российском формате или адрес почты — вход принимает и то и другое,
             *     что именно, сервер решает по наличию собачки. Регэксп покрывает обе формы
             *     сразу: разбить на два поля значило бы заставить фронт угадывать до отправки.
             * @example +79991234567
             */
            login: string;
            /**
             * @description Секрет, выданный при запросе входа: без него статус чужого номера не опросить
             * @example 3f2a9c1d4b5e6f708192a3b4c5d6e7f8
             */
            sessionId: string;
        };
        UserDto: {
            /**
             * @description Телефон, если входили по нему; иначе null
             * @example +79991234567
             */
            phone: string | null;
            /**
             * @description Подтверждённая почта; null — ещё не привязана. На неё уходит решение
             *     модератора, поэтому без неё отзыв оставить нельзя.
             * @example me@example.com
             */
            email: string | null;
            /**
             * @description Публичный ник; им подписаны отзывы
             * @example maxim_n
             */
            nickname: string;
            /** @description Идентификатор пользователя */
            id: string;
            /**
             * @description false — ник сгенерирован автоматически и пользователь его ещё не выбирал.
             *     Фронт по этому флагу показывает обязательный шаг ввода ника.
             */
            nicknameConfirmed: boolean;
            /**
             * @description false — пользователь не принимал пользовательское соглашение и не давал
             *     согласия на обработку персональных данных. Фронт по этому флагу
             *     показывает блокирующее окно; у аккаунтов, заведённых до появления
             *     согласия, флаг тоже false.
             */
            consentAccepted: boolean;
        };
        SessionStatusDto: {
            /**
             * @description `pending` — ждём подтверждения на SIM-карте; `needs-code` — SIM-PUSH не
             *     сработал, провайдер прислал код в SMS и надо показать поле ввода;
             *     `confirmed` — вход состоялся и в ответе есть токен; `failed` — провайдер
             *     аутентификацию не подтвердил; `expired` — попытка истекла или секрет
             *     не подошёл. Последние два лечатся новым запросом входа.
             * @enum {string}
             */
            status: "pending" | "needs-code" | "confirmed" | "failed" | "expired";
            /** @description Только при `confirmed` */
            accessToken?: string;
            /** @description Только при `confirmed` */
            user?: components["schemas"]["UserDto"];
        };
        VerifyCodeDto: {
            /**
             * @description Телефон в российском формате или адрес почты — вход принимает и то и другое,
             *     что именно, сервер решает по наличию собачки. Регэксп покрывает обе формы
             *     сразу: разбить на два поля значило бы заставить фронт угадывать до отправки.
             * @example +79991234567
             */
            login: string;
            /**
             * @description Код из SMS. Длина не фиксирована: код выдаёт провайдер, и в тестовом режиме
             *     он четырёхзначный (1234), а в боевом может быть длиннее.
             * @example 1234
             */
            code: string;
        };
        AuthResponseDto: {
            /** @description Bearer-токен для заголовка Authorization */
            accessToken: string;
            /** @description Профиль вошедшего пользователя */
            user: components["schemas"]["UserDto"];
        };
        EmailDto: {
            /** @example me@example.com */
            email: string;
        };
        VerifyEmailDto: {
            /** @example me@example.com */
            email: string;
            /**
             * @description Код из письма; свой, шестизначный — в отличие от кода провайдера
             * @example 123456
             */
            code: string;
        };
        SetNicknameDto: {
            /**
             * @description Никнейм: буквы, цифры и подчёркивание, 3–20 символов. Пробелов нет
             *     намеренно — ник подписывает отзывы и читается как идентификатор.
             *     Занятость проверяется без учёта регистра.
             * @example maxim_n
             */
            nickname: string;
        };
        HousePinDto: {
            /** @description Идентификатор дома */
            id: string;
            /** @description Отображаемый адрес */
            address: string;
            lat: number;
            lon: number;
            /** @description Подтверждённых отзывов по всем квартирам дома; других публично не существует */
            confirmedCount: number;
        };
        HouseSlugsDto: {
            /** @example moskva */
            citySlug: string;
            /** @example tverskaya-ulica */
            streetSlug: string;
            /** @example 12 */
            houseSlug: string;
        };
        ApartmentSummaryDto: {
            /** @description Идентификатор квартиры */
            id: string;
            /** @description Номер квартиры */
            number: string;
            /** @description Подъезд */
            entrance: string;
            /** @description Подтверждённых отзывов */
            confirmedCount: number;
        };
        HouseWithApartmentsDto: {
            /** @description Части URL публичной страницы; null — адрес дома не разобрался на город и улицу */
            slug: components["schemas"]["HouseSlugsDto"] | null;
            /** @description Квартиры дома, по которым есть подтверждённые отзывы */
            apartments: components["schemas"]["ApartmentSummaryDto"][];
            id: string;
            address: string;
            lat: number;
            lon: number;
        };
        HouseLookupResponseDto: {
            /** @description null — по этому адресу ещё нет ни одного отзыва */
            house: components["schemas"]["HouseWithApartmentsDto"] | null;
            /**
             * @description Слаги для ссылки на страницу дома. Считаются и когда дома ещё нет в базе:
             *     фронт не должен повторять транслитерацию, иначе его вариант разойдётся с
             *     сохранённым — например, когда номер получил суффикс из-за коллизии.
             */
            slug: components["schemas"]["HouseSlugsDto"] | null;
        };
        /** @enum {string} */
        ReviewStatus: "pending" | "confirmed" | "rejected";
        MyReviewDto: {
            status: components["schemas"]["ReviewStatus"];
            /**
             * @description Оценка от 1 до 5; null — отзыв написан до появления рейтинга
             * @example 4
             */
            rating: number | null;
            /**
             * @description Начало периода съёма, месяц и год
             * @example 2024-03
             */
            periodFrom: string | null;
            /**
             * @description Конец периода съёма, месяц и год
             * @example 2025-04
             */
            periodTo: string | null;
            /** @description Причина отклонения от модератора; null — отзыв не отклоняли */
            rejectionReason: string | null;
            /**
             * @description Номер квартиры
             * @example 120
             */
            apartmentNumber: string;
            /**
             * @description Подъезд
             * @example 7
             */
            entrance: string;
            /** @description Части URL публичной страницы дома; null — адрес не разобрался */
            slug: components["schemas"]["HouseSlugsDto"] | null;
            /**
             * @description Уровень доверия: high — предоставлена запись регистрации права из ЕГРН,
             *     low — указан только кадастровый номер или ЕГРН не указан вовсе.
             * @enum {string}
             */
            trustLevel: "high" | "low";
            /** @description Идентификатор отзыва */
            id: string;
            /** @description Текст отзыва */
            text: string;
            /** @description Дата создания, ISO 8601 */
            createdAt: string;
            /** @description Дата последней правки, ISO 8601; по ней отсортирован список */
            updatedAt: string;
            /** @description Идентификатор квартиры, о которой отзыв */
            apartmentId: string;
            /** @description Адрес дома */
            address: string;
            /** @description Широта дома — к этой точке перелетает карта */
            lat: number;
            /** @description Долгота дома */
            lon: number;
        };
        CreateReviewDto: {
            /**
             * @description Номер квартиры
             * @example 120
             */
            apartmentNumber: string;
            /**
             * @description Подъезд; обязателен — API Яндекса его не отдаёт, вводится вручную
             * @example 7
             */
            entrance: string;
            /**
             * @description Кадастровый номер из выписки ЕГРН: округ:район:квартал:объект.
             *     Квартал — шесть или семь цифр, номер объекта — от одной.
             *     Опционален; если не передан ни он, ни `regRecord`, отзыв получает низкий уровень доверия.
             * @example 77:01:0001075:1234
             */
            egrn?: string;
            /**
             * @description Запись регистрации права из выписки ЕГРН.
             *     Формат: {кадастровый_номер}-{регион}/{отдел}/{год}-{порядковый_номер}.
             *     Опциональна; при наличии даёт отзыву высокий уровень доверия.
             * @example 77:01:0003036:1308-77/011/2018-1
             */
            regRecord?: string;
            /**
             * @description Оценка квартиры от 1 до 5
             * @example 4
             */
            rating: number;
            /**
             * @description Начало периода съёма, месяц и год
             * @example 2024-03
             */
            periodFrom?: string;
            /**
             * @description Конец периода съёма, месяц и год
             * @example 2025-04
             */
            periodTo?: string;
            /** @description Канонический адрес дома от геокодера */
            address: string;
            /** @description Широта дома */
            lat: number;
            /** @description Долгота дома */
            lon: number;
            /** @description Текст отзыва */
            text: string;
            /** @description Токен SmartCaptcha; обязателен, когда проверка капчи включена */
            captchaToken?: string;
        };
        ReviewCreatedDto: {
            status: components["schemas"]["ReviewStatus"];
            reviewId: string;
            houseId: string;
            apartmentId: string;
        };
        UpdateReviewDto: {
            /**
             * @description Оценка квартиры от 1 до 5
             * @example 4
             */
            rating: number;
            /**
             * @description Начало периода съёма, месяц и год
             * @example 2024-03
             */
            periodFrom?: string;
            /**
             * @description Конец периода съёма, месяц и год
             * @example 2025-04
             */
            periodTo?: string;
            /** @description Текст отзыва */
            text: string;
            /** @description Токен SmartCaptcha; обязателен, когда проверка капчи включена */
            captchaToken?: string;
        };
        ReviewDto: {
            status: components["schemas"]["ReviewStatus"];
            /**
             * @description Оценка от 1 до 5; null — отзыв написан до появления рейтинга
             * @example 4
             */
            rating: number | null;
            /**
             * @description Начало периода съёма, месяц и год
             * @example 2024-03
             */
            periodFrom: string | null;
            /**
             * @description Конец периода съёма, месяц и год
             * @example 2025-04
             */
            periodTo: string | null;
            /**
             * @description Уровень доверия: high — предоставлена запись регистрации права из ЕГРН,
             *     low — указан только кадастровый номер или ЕГРН не указан вовсе.
             * @enum {string}
             */
            trustLevel: "high" | "low";
            /** @description Идентификатор отзыва */
            id: string;
            /** @description Никнейм автора */
            authorName: string;
            /** @description Текст отзыва */
            text: string;
            /** @description Дата создания, ISO 8601 */
            createdAt: string;
        };
        CityListItemDto: {
            /** @example moskva */
            citySlug: string;
            /** @example Москва */
            cityName: string;
            /** @description Домов с подтверждёнными отзывами */
            houseCount: number;
            /** @description Подтверждённых отзывов по всему городу */
            reviewCount: number;
        };
        StreetListItemDto: {
            /** @example tverskaya-ulica */
            streetSlug: string;
            /** @example Тверская улица */
            streetName: string;
            /**
             * @description Средняя оценка по улице, округлённая до десятых; null — ни одной оценки
             * @example 4.3
             */
            ratingAvg: number | null;
            houseCount: number;
            reviewCount: number;
        };
        CityPageDto: {
            /** @example moskva */
            citySlug: string;
            /** @example Москва */
            cityName: string;
            streets: components["schemas"]["StreetListItemDto"][];
            houseCount: number;
            reviewCount: number;
            /** @description Всего улиц в городе: по нему считается число страниц */
            streetCount: number;
        };
        StreetHouseDto: {
            /** @example 12 */
            houseSlug: string;
            /**
             * @description Номер дома как в адресе: «12с17»
             * @example 12с17
             */
            houseNumber: string;
            /** @example 4.3 */
            ratingAvg: number | null;
            id: string;
            address: string;
            reviewCount: number;
        };
        StreetPageDto: {
            /** @example moskva */
            citySlug: string;
            /** @example Москва */
            cityName: string;
            /** @example tverskaya-ulica */
            streetSlug: string;
            /** @example Тверская улица */
            streetName: string;
            /** @example 4.3 */
            ratingAvg: number | null;
            houses: components["schemas"]["StreetHouseDto"][];
            reviewCount: number;
            /** @description Всего домов на улице */
            houseCount: number;
        };
        HouseApartmentDto: {
            /** @example 120 */
            number: string;
            /** @example 7 */
            entrance: string;
            /** @example 4.3 */
            ratingAvg: number | null;
            id: string;
            reviewCount: number;
        };
        HouseReviewDto: {
            status: components["schemas"]["ReviewStatus"];
            /** @example 4 */
            rating: number | null;
            /** @example 2024-03 */
            periodFrom: string | null;
            /** @example 2025-04 */
            periodTo: string | null;
            /**
             * @description Уровень доверия: high — предоставлена запись регистрации права из ЕГРН,
             *     low — указан только кадастровый номер или ЕГРН не указан вовсе.
             * @enum {string}
             */
            trustLevel: "high" | "low";
            /** @example 120 */
            apartmentNumber: string;
            /** @example 7 */
            entrance: string;
            id: string;
            /** @description Никнейм автора */
            authorName: string;
            text: string;
            /** @description Дата создания, ISO 8601 */
            createdAt: string;
            apartmentId: string;
        };
        HousePageDto: {
            /** @example moskva */
            citySlug: string;
            /** @example Москва */
            cityName: string;
            /** @example tverskaya-ulica */
            streetSlug: string;
            /** @example Тверская улица */
            streetName: string;
            /** @example 12 */
            houseSlug: string;
            /** @example 12с17 */
            houseNumber: string;
            /**
             * @description Средняя оценка, округлённая до десятых; null — ни у одного отзыва нет оценки
             * @example 4.3
             */
            ratingAvg: number | null;
            /** @description Дата последнего изменения отзывов, ISO 8601; из неё берётся lastmod в sitemap */
            updatedAt: string | null;
            apartments: components["schemas"]["HouseApartmentDto"][];
            reviews: components["schemas"]["HouseReviewDto"][];
            id: string;
            /** @description Полный адрес от геокодера */
            address: string;
            lat: number;
            lon: number;
            /** @description Подтверждённых отзывов по всему дому */
            reviewCount: number;
            /** @description Отзывов с оценкой; в разметке это reviewCount у aggregateRating */
            ratingCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    AuthController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResponseDto"];
                };
            };
            /** @description Не пройдена проверка капчи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Вход по этому номеру запрошен меньше минуты назад */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Провайдер недоступен — войти сейчас нельзя */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_pollSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPollDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusDto"];
                };
            };
        };
    };
    AuthController_mobileIdCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Уведомление принято */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Неверный, истёкший код или исчерпаны попытки */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_acceptConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_requestEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailDto"];
            };
        };
        responses: {
            /** @description Код отправлен на указанную почту */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Почта уже используется другим аккаунтом */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Код на эту почту запрошен меньше минуты назад */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не удалось отправить письмо */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Неверный, истёкший код или исчерпаны попытки */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Почта уже используется другим аккаунтом */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_setNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetNicknameDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Никнейм уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HousesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousePinDto"][];
                };
            };
        };
    };
    HousesController_byAddress: {
        parameters: {
            query: {
                /** @description Канонический адрес, как его вернул геокодер */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseLookupResponseDto"];
                };
            };
        };
    };
    ReviewsController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyReviewDto"][];
                };
            };
            /** @description Нет или истёк токен авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCreatedDto"];
                };
            };
            /** @description Нет или истёк токен авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не пройдена проверка капчи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyReviewDto"];
                };
            };
            /** @description Нет или истёк токен авторизации */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не пройдена проверка капчи */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Своего отзыва с таким идентификатором нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Отзыв на проверке у модератора */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApartmentReviewsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"][];
                };
            };
        };
    };
    CatalogController_cities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityListItemDto"][];
                };
            };
        };
    };
    CatalogController_city: {
        parameters: {
            query?: {
                /** @description Номер страницы, с единицы */
                page?: number;
            };
            header?: never;
            path: {
                citySlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityPageDto"];
                };
            };
        };
    };
    CatalogController_street: {
        parameters: {
            query?: {
                /** @description Номер страницы, с единицы */
                page?: number;
            };
            header?: never;
            path: {
                citySlug: string;
                streetSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreetPageDto"];
                };
            };
        };
    };
    CatalogController_house: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                citySlug: string;
                streetSlug: string;
                houseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousePageDto"];
                };
            };
        };
    };
}
